[package]
name = "sqs-replay"
version = "0.1.0"
authors = ["stustill <stuart.still@goji.investments>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.40.0"
rusoto_sqs = "0.40.0"
clap = "2.33.0"